/* Enable foreign keys */
PRAGMA foreign_keys = ON;

/* USERS table is a list of signed up users */
CREATE TABLE USERS (
	USER_ID INTEGER PRIMARY KEY NOT NULL,
	EMAIL TEXT NOT NULL,
	NICKNAME TEXT /* NOT NULL */
);

/* CATEGORIES table is a list of categories created by users */
CREATE TABLE CATEGORIES (
	CATEGORY_ID INTEGER PRIMARY KEY NOT NULL,
	NICKNAME TEXT NOT NULL,
	USER_ID INTEGER NOT NULL,
	ICON BLOB, /* NOT NULL */
	DESCRIPTION TEXT,
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);

/* PLACES table is a list of places that were added to at least one of the existed categories */
CREATE TABLE PLACES (
	PLACE_ID INTEGER PRIMARY KEY NOT NULL,
	NICKNAME TEXT NOT NULL,
	COORDINATES TEXT NOT NULL,
	DESCRIPTION TEXT
);

/* CATEGORIES_PLACES table represents the relationship between existing categories and places */
CREATE TABLE CATEGORIES_PLACES (
	CATEGORY_ID INTEGER NOT NULL,
	PLACE_ID INTEGER NOT NULL,
	FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID) ON DELETE CASCADE,
	FOREIGN KEY(PLACE_ID) REFERENCES PLACES(PLACE_ID)
);
